optical character recognition is used to extract text from image or pdf. we will use pytesseract, its a library for ocr, it is open source.

In [ ]:
!apt-get install -y tesseract-ocr
!pip install pytesseract

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
Collecting pytesseract
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.11/dist-packages (from pytesseract) (24.2)
Requirement already satisfied: Pillow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from pytesseract) (11.1.0)
Downloading pytesseract-0.3.13-py3-none-any.whl (14 kB)
Installing collected packages: pytesseract
Successfully installed pytesseract-0.3.13

In [ ]:
import pytesseract
from PIL import Image
import cv2
# PIL is the python imaging library which provides the python interpreter with image editing capabilities.
# This is so because python cannot directly edit the image. The Image module provides a class with the same name
# which is used to represent the PIL image.

In [ ]:
img=Image.open("img1.png")
text=pytesseract.image_to_string(img)
print(text)

KEEP
CALM

CAUSE | KNOW

1AM
AWESOME

In [ ]:
img=Image.open("img2.jpg")
text=pytesseract.image_to_string(img)
print(text)

Aa Bb Co Dd Ee FF Gg Hh Ti
Jj KK LI Mm Nn Oo Pp Qq

RrSsTt Uu W Ww Xx Jy Zz
@0123456789()?!:,-+

In [ ]:
img1=cv2.imread("img1.png")
img1 # BGR
img1_rgb=cv2.cvtColor(img1,cv2.COLOR_BGR2RGB)
text=pytesseract.image_to_string(img1_rgb)
print(text)

KEEP
CALM

CAUSE | KNOW

1AM
AWESOME

In [ ]:
img2=cv2.imread("img2.jpg")
img2 # BGR
img2_rgb = cv2.cvtColor(img2,cv2.COLOR_BGR2RGB)
text = pytesseract.image_to_string(img2_rgb)
print(text)

da Bb Cc Dd Ee FF Gg Hh Ti
Jj KK LI Mm Nn Oo Pp Qq

RrSsTt Uu W Ww Xx Yy Zz
@0123456789()?!:-+

In [ ]:
print(pytesseract.image_to_boxes(img1_rgb))

K 62 155 84 182 0
E 87 155 104 182 0
E 88 155 126 182 0
P 108 155 148 182 0
C 51 113 76 140 0
A 77 114 106 140 0
L 109 114 127 140 0
M 130 114 156 140 0
C 41 91 52 103 0
A 53 91 66 103 0
U 55 91 75 103 0
S 67 91 78 103 0
E 80 91 98 103 0
| 105 91 107 103 0
K 114 91 124 103 0
N 126 91 136 103 0
O 138 91 151 103 0
W 152 91 168 103 0
1 66 53 71 79 0
A 85 53 113 79 0
M 116 53 143 79 0
A 8 11 36 38 0
W 38 11 73 38 0
E 46 11 95 38 0
S 76 11 115 38 0
O 118 11 146 38 0
M 126 11 176 38 0
E 150 11 199 38 0

In [ ]:
df=pytesseract.image_to_data(img1_rgb,output_type="data.frame")
df
# the -1 means that the item is not a word. the high confidence results are generally
# the one's which have the conf of greater than 60

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text
0,1,1,0,0,0,0,0,0,208,243,-1,NaN
1,2,1,1,0,0,0,51,61,105,69,-1,NaN
2,3,1,1,1,0,0,51,61,105,69,-1,NaN
3,4,1,1,1,1,0,62,61,86,27,-1,NaN
4,5,1,1,1,1,1,62,61,86,27,96,KEEP
5,4,1,1,1,2,0,51,103,105,27,-1,NaN
6,5,1,1,1,2,1,51,103,105,27,95,CALM
7,2,1,2,0,0,0,41,140,127,12,-1,NaN
8,3,1,2,1,0,0,41,140,127,12,-1,NaN
9,4,1,2,1,1,0,41,140,127,12,-1,NaN
10,5,1,2,1,1,1,41,140,57,12,83,CAUSE
11,5,1,2,1,1,2,105,140,2,12,81,|
12,5,1,2,1,1,3,114,140,54,12,96,KNOW
13,2,1,3,0,0,0,8,164,191,68,-1,NaN
14,3,1,3,1,0,0,8,164,191,68,-1,NaN
15,4,1,3,1,1,0,66,164,77,26,-1,NaN
16,5,1,3,1,1,1,66,164,77,26,69,1AM
17,4,1,3,1,2,0,8,205,191,27,-1,NaN
18,5,1,3,1,2,1,8,205,191,27,96,AWESOME

In [ ]:
img3=cv2.imread("invoice 1.jpg")
img3 # BGR
img3_rgb = cv2.cvtColor(img3,cv2.COLOR_BGR2RGB)
text = pytesseract.image_to_string(img3_rgb)
print(text)

Business Name
123 Street Address, City, State, Zip

Website, Email Address

Contact Number



BILLTO SHIP TO

ABC Enterprise ABC Enterprise Invoice Date: 01/02/2022

DESCRIPTION UN aslo





0.00

0.00

0.00

0.00

0.00

0.00

0.00

Thank you for your business! SUBTOTAL 0.00
DISCOUNT 0.00

svete go

Terms & Instructions: TAX RATE 0.00%
TOTAL TAX 0.00

SHIPPING/ HANDLING 0.00

Balance bus € 1000.00

In [ ]:
import re

re.search(r"[0-9]{2}/[0-9]{2}/[0-9]{4}",text).group()

'02/05/2022'

In [ ]:
re.findall(r"[0-9]{2}/[0-9]{2}/[0-9]{4}",text)

['01/02/2022']

In [ ]:
df=pytesseract.image_to_data(img3_rgb,output_type="data.frame")
df

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text
0,1,1,0,0,0,0,0,0,1275,1650,-1,NaN
1,2,1,1,0,0,0,231,66,335,77,-1,NaN
2,3,1,1,1,0,0,231,66,335,77,-1,NaN
3,4,1,1,1,1,0,231,66,286,30,-1,NaN
4,5,1,1,1,1,1,231,66,164,30,96,Business
...,...,...,...,...,...,...,...,...,...,...,...,...
115,4,1,11,1,1,0,898,1394,303,80,-1,NaN
116,5,1,11,1,1,1,898,1418,99,33,96,Balance
117,5,1,11,1,1,2,1004,1394,43,80,0,bus
118,5,1,11,1,1,3,1080,1394,14,80,58,€
119,5,1,11,1,1,4,1100,1394,101,80,85,1000.00

In [ ]:
for i,t in enumerate(df["text"]):
  print(i,t)

0 nan
1 nan
2 nan
3 nan
4 Business
5 Name
6 nan
7 123
8 Street
9 Address,
10 City,
11 State,
12 Zip
13 nan
14 nan
15 nan
16 Website,
17 Email
18 Address
19 nan
20 nan
21 nan
22 Contact
23 Number
24 nan
25 nan
26 nan
27
28 nan
29 nan
30 nan
31 BILLTO
32 SHIP
33 TO
34 nan
35 nan
36 nan
37 ABC
38 Enterprise
39 ABC
40 Enterprise
41 Invoice
42 Date:
43 01/02/2022
44 nan
45 nan
46 nan
47 DESCRIPTION
48 UN
49 aslo
50 nan
51 nan
52 nan
53
54 nan
55 nan
56 nan
57
58 nan
59 nan
60 nan
61 0.00
62 nan
63 nan
64 0.00
65 nan
66 nan
67 0.00
68 nan
69 nan
70 0.00
71 nan
72 nan
73 0.00
74 nan
75 nan
76 0.00
77 nan
78 nan
79 0.00
80 nan
81 nan
82 Thank
83 you
84 for
85 your
86 business!
87 SUBTOTAL
88 0.00
89 nan
90 DISCOUNT
91 0.00
92 nan
93 nan
94 svete
95 go
96 nan
97 nan
98 Terms
99 &
100 Instructions:
101 TAX
102 RATE
103 0.00%
104 nan
105 TOTAL
106 TAX
107 0.00
108 nan
109 nan
110 SHIPPING/
111 HANDLING
112 0.00
113 nan
114 nan
115 nan
116 Balance
117 bus
118 €
119 1000.00

In [ ]:
print(df["text"][43])

01/02/2022

In [ ]:
print(df["text"][119])

1000.00

In [ ]:
img4=cv2.imread("invoice 2.jpg")
img4 # BGR
img4_rgb = cv2.cvtColor(img4,cv2.COLOR_BGR2RGB)
text = pytesseract.image_to_string(img4_rgb)
print(text)

Business Name
123 Street Address, City, State, Zip

Website, Email Address

Contact Number



BILLTO SHIP TO

XYZ Enterprise XYZ Enterprise Invoice Date: 02/05/2022

DESCRIPTION UN aslo





0.00

0.00

0.00

0.00

0.00

0.00

0.00

Thank you for your business! SUBTOTAL 0.00
DISCOUNT 0.00

svete go

Terms & Instructions: TAX RATE 0.00%
TOTAL TAX 0.00

SHIPPING/ HANDLING 0.00

Balance Due € 1800.00

In [ ]:
re.findall(r"[0-9]{2}/[0-9]{2}/[0-9]{4}",text)

['02/05/2022']

In [ ]:
df2=pytesseract.image_to_data(img4_rgb,output_type="data.frame")
df2

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text
0,1,1,0,0,0,0,0,0,1275,1650,-1,NaN
1,2,1,1,0,0,0,231,66,335,77,-1,NaN
2,3,1,1,1,0,0,231,66,335,77,-1,NaN
3,4,1,1,1,1,0,231,66,286,30,-1,NaN
4,5,1,1,1,1,1,231,66,164,30,96,Business
...,...,...,...,...,...,...,...,...,...,...,...,...
115,4,1,11,1,1,0,898,1394,303,80,-1,NaN
116,5,1,11,1,1,1,898,1418,99,33,96,Balance
117,5,1,11,1,1,2,1004,1394,43,80,39,Due
118,5,1,11,1,1,3,1080,1394,14,80,53,€
119,5,1,11,1,1,4,1100,1394,101,80,85,1800.00

In [ ]:
for i,t in enumerate(df2["text"]):
  print(i,t)

0 nan
1 nan
2 nan
3 nan
4 Business
5 Name
6 nan
7 123
8 Street
9 Address,
10 City,
11 State,
12 Zip
13 nan
14 nan
15 nan
16 Website,
17 Email
18 Address
19 nan
20 nan
21 nan
22 Contact
23 Number
24 nan
25 nan
26 nan
27
28 nan
29 nan
30 nan
31 BILLTO
32 SHIP
33 TO
34 nan
35 nan
36 nan
37 XYZ
38 Enterprise
39 XYZ
40 Enterprise
41 Invoice
42 Date:
43 02/05/2022
44 nan
45 nan
46 nan
47 DESCRIPTION
48 UN
49 aslo
50 nan
51 nan
52 nan
53
54 nan
55 nan
56 nan
57
58 nan
59 nan
60 nan
61 0.00
62 nan
63 nan
64 0.00
65 nan
66 nan
67 0.00
68 nan
69 nan
70 0.00
71 nan
72 nan
73 0.00
74 nan
75 nan
76 0.00
77 nan
78 nan
79 0.00
80 nan
81 nan
82 Thank
83 you
84 for
85 your
86 business!
87 SUBTOTAL
88 0.00
89 nan
90 DISCOUNT
91 0.00
92 nan
93 nan
94 svete
95 go
96 nan
97 nan
98 Terms
99 &
100 Instructions:
101 TAX
102 RATE
103 0.00%
104 nan
105 TOTAL
106 TAX
107 0.00
108 nan
109 nan
110 SHIPPING/
111 HANDLING
112 0.00
113 nan
114 nan
115 nan
116 Balance
117 Due
118 €
119 1800.00

In [ ]:
print(df2["text"][43])

02/05/2022

In [ ]:
print(df2["text"][119])

1800.00

In [ ]:
img5=cv2.imread("invoice 3.jpg")
img5 # BGR
img5_rgb = cv2.cvtColor(img4,cv2.COLOR_BGR2RGB)
text = pytesseract.image_to_string(img5_rgb)
print(text)

Business Name
123 Street Address, City, State, Zip

Website, Email Address

Contact Number



BILLTO SHIP TO

XYZ Enterprise XYZ Enterprise Invoice Date: 02/05/2022

DESCRIPTION UN aslo





0.00

0.00

0.00

0.00

0.00

0.00

0.00

Thank you for your business! SUBTOTAL 0.00
DISCOUNT 0.00

svete go

Terms & Instructions: TAX RATE 0.00%
TOTAL TAX 0.00

SHIPPING/ HANDLING 0.00

Balance Due € 1800.00

In [ ]:
import os
invoices = os.listdir("INVOICES")
print(invoices)

['invoice 3.jpg', 'invoice 2.jpg', '.ipynb_checkpoints', 'invoice 1.jpg']

In [ ]:
import pandas as pd

In [ ]:
prices=[]
dates=[]
for i in invoices:
  invoice=cv2.imread(f"INVOICES/{i}")
  invoice_rgb=cv2.cvtColor(invoice,cv2.COLOR_BGR2RGB)
  text=pytesseract.image_to_string(invoice_rgb)
  df=pytesseract.image_to_data(invoice_rgb,output_type="data.frame")
  dates.append(df["text"][43])
  prices.append(df["text"][119])
print(dates)
print(prices)

error: OpenCV(4.11.0) /io/opencv/modules/imgproc/src/color.cpp:199: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Date': dates,
    'Price': prices
})
df

         Date    Price
0  02/04/2022  2000.00
1  02/05/2022  1800.00